spring:
  application:
    name: weather-report-gateway
server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
feign:
  client:
    config:
      feiginName:
        connectTimeout: 5000
        readTimeout: 5000